name: Python CI

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "drum/**"
      - "setup.cfg"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "drum/**"
      - "setup.cfg"

defaults:
  run:
    working-directory: ./

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          pytest drum/

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mypy
        run: python -m mypy drum/

      - name: Run flake8
        run: python -m flake8 drum/
